services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: newsletter-redis-commander
    environment:
      REDIS_HOSTS: "local:redis:6379"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8081"
    networks:
      - newsletter-network
    depends_on:
      - redis


volumes:
  redis_data:
    driver: local

networks:
  newsletter-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
